services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "3306:3306"
    networks:
      - taskflow_network
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql

  backend:
    image: ${BACKEND_IMAGE}
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/var/www/html
    depends_on:
      - database
    networks:
      - taskflow_network

  frontend:
    image: ${FRONTEND_IMAGE}
    env_file: ./frontend/.env
    ports:
      - "80:80"
    volumes:
      - frontend-data:/var/www/html
      - nginx-conf:/etc/nginx
    depends_on:
      - backend
    networks:
      - taskflow_network

networks:
  taskflow_network:
    driver: bridge

volumes:
  frontend-data:
  backend-data:
  nginx-conf:
  mysql-data:
  mysql-conf:
