version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "taskflow_db"
    ports:
      - "3306:3306"
    networks:
      - taskflow_network

  backend:
    image: ${BACKEND_IMAGE}
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - taskflow_network

networks:
  taskflow_network:
    driver: bridge
